### ISSUE TITLE
Language "deinprogramm": Record definition does not work

### ISSUE THREAD

**Issue by simons1008** [rmculpepper/iracket#16]
[define-record-working.txt](https://github.com/rmculpepper/iracket/files/7006041/define-record-working.txt)
Hello, I am working with the language "deinprogramm" (see textbook "Schreibe dein Programm" by Mike Sperber and Herbert Klaeren). The attached code snippet works perfectly in the Editor window of DrRacket. 

But in the Jupyter/iRacket environment 
(define-record computer make-computer ...) 
provokes the error message:  
make-computer: unbound identifier;
 also, no #%top syntax transformer is bound
  in: make-computer
  
I tried the attached code snippet in the REPL window of DrRacket and got the same error message. 

Do you have an explanation for this behaviour?

**Comment by rmculpepper** [comment]
There are some things that work inside modules (and the definitions window is actually treated as a module) but not at the REPL. Google for Racket and "the top level is hopeless", because of the difference in the order of expansion and the discovery of bound names. An IRacket notebook is essentially just a REPL, so it makes sense that your example wouldn't work there either.

You could try filing a bug report in the deinprogramm repository. It's sometimes possible to fix macros like `define-record` to work at the REPL by using the `(define-values (name ...) (values))` trick to declare names before their definitions. I think that might be the issue in this case, but I'm not sure.

**Comment by simons1008** [comment]
Thank you, that helps.
